[io] add support for reading CSV files from http and https URLs
SciNim/Datamancer pull request #32
Opened 2022-06-26 20:02 UTC by AngelEzquerra

Make it possible to specify a web URL as the fname argument of readCsv. If fname starts with http or https the file _contents_ will be automatically downloaded before being parsed. Note that no catching is performed (i.e. the file contents are downloaded every time) and that -d:ssl is needed in order to download from https URLs.

2022-06-27 07:42 UTC, Vindaar requested changes
Could you add a line to the changelog? (changelog.org in the repository root; just add a `v0.2.5` above the `v0.2.4` and add a bullet point about this)

2022-06-27 07:42 UTC, Vindaar commented on src/datamancer/io.nim
> +  ## web server. No catching is performed so if you plan to read from the same
```suggestion
  ## web server. No caching is performed so if you plan to read from the same
```

2022-06-27 07:42 UTC, Vindaar commented on src/datamancer/io.nim
> +  ## arguments are ignored when reading from a web URL.
Given that the missing `skipInitialSpace` and `quote` is just an oversight feel free to fix it (or I'll do it in a follow up for this and the regular case.

2022-06-27 07:42 UTC, Vindaar commented on src/datamancer/io.nim
> +  ## web server. No catching is performed so if you plan to read from the same
Note that we adding caching wouldn't really be hard. One could use `getTempDir` from the stdlib and write the contents to a file. Then upon downloading a file we'd first check if a file of the same name (i.e. from last part of the URL) exists in the temp dir.

However, for now maybe it's better to keep it simple (caching then also opens up the question of "should we overwrite if some time has elapsed", adding a `force` option to always download, making sure we actually get the same directory from `getTempDir` { I think it always gives you a new one } etc.). So this is fine (and I was just thinking out loud).

2022-06-27 09:38 UTC, AngelEzquerra commented on src/datamancer/io.nim
> +  ## web server. No catching is performed so if you plan to read from the same
Actually I think that not caching by default is the right behavior. As a user, I'd expect that if the remote file changes, reading it should get the updated data. As you said we could add a `cache` flag (disabled by default IMO) but for now the user can always download the file manually relatively easily if they wanted to. However, I thought it was important to highlight that we don't cache in case people expect a different behavior (since I believe that Keras does caching, for example).

2022-06-28 07:40 UTC, merged

2022-06-28 07:40 UTC, Vindaar commented
Thanks a lot for this! Really appreciated. :rocket: